version: '2'
services:
  web:
    build:
      context: .
    container_name: app
    ports:
      - "80:80"
      - "433:433"
    volumes:
      - ./app:/var/www/html
    links:
      - db
  db:
    image: mysql
    container_name: db
    volumes:
      - var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=phprs
      - MYSQL_DATABASE=phprs
    volumes:
    - "./db:/docker-entrypoint-initdb.d"
